import { defineConfig } from 'vitepress'

export default defineConfig({
  base: '/iflycode-reverse-engineer/',
  title: 'iFlyCode 逆向分析文档',
  description: '讯飞星火飞码 JetBrains 插件通信协议逆向分析',
  lang: 'zh-CN',
  lastUpdated: true,
  ignoreDeadLinks: true,
  markdown: {
    lineNumbers: true,
  },
  themeConfig: {
    search: {
      provider: 'local',
    },
    nav: [
      { text: '文档首页', link: '/' },
      { text: 'GitHub', link: 'https://github.com/vibe-coding-labs/iflycode-reverse-engineer' },
    ],
    sidebar: [
      // === 架构与基础设施 ===
      {
        text: '架构与基础设施',
        items: [
          { text: '整体架构', link: '/01-architecture' },
          { text: 'Agent 进程管理', link: '/02-agent-process' },
          { text: '服务端端点', link: '/03-server-endpoints' },
          { text: '通信协议', link: '/04-websocket-protocol' },
          { text: '消息格式定义', link: '/05-message-formats' },
          { text: '命令体系参考', link: '/06-command-reference' },
          { text: 'WebView JS Bridge', link: '/07-webview-bridge' },
        ],
      },
      // === 功能流程 ===
      {
        text: '功能流程',
        items: [
          { text: '用户认证流程', link: '/08-auth-flow' },
          { text: '智能对话协议', link: '/09-chat-protocol' },
          { text: '代码补全协议', link: '/10-code-complete-protocol' },
          { text: '内联聊天协议', link: '/11-inline-chat-protocol' },
          { text: 'SQL 生成/优化', link: '/12-sql-protocol' },
          { text: '单元测试协议', link: '/13-unit-test-protocol' },
          { text: 'Git 评审协议', link: '/14-git-review-protocol' },
          { text: '代码搜索协议', link: '/15-code-search-protocol' },
          { text: '代码检查协议', link: '/16-code-check-protocol' },
        ],
      },
      // === 运维与监控 ===
      {
        text: '运维与监控',
        items: [
          { text: '心跳与错误恢复', link: '/17-heartbeat-error' },
          { text: 'Telemetry 遥测', link: '/18-telemetry' },
          { text: '设置同步协议', link: '/19-settings-protocol' },
          { text: '枚举值参考', link: '/20-enums-reference' },
        ],
      },
      // === 逆向分析核心 ===
      {
        text: '逆向分析核心',
        items: [
          { text: '混淆技术分析', link: '/21-obfuscation' },
          { text: 'Agent Cloud 协议', link: '/22-agent-cloud-protocol' },
          { text: 'Agent 内部架构', link: '/23-agent-internals' },
          { text: '动作系统', link: '/24-action-system' },
          { text: '内联聊天 UI', link: '/25-inline-chat-ui' },
          { text: '模板系统', link: '/26-template-system' },
          { text: '编辑器集成', link: '/27-editor-integration' },
          { text: '监听器事件', link: '/28-listener-events' },
          { text: '混淆字符串', link: '/29-obfuscated-strings' },
          { text: 'WebView 前端', link: '/30-webview-frontend' },
          { text: 'Agent 二进制分析', link: '/31-agent-binary-analysis' },
          { text: '代码补全流程', link: '/32-code-complete-flow' },
          { text: 'Q 包分析', link: '/33-Q-package-analysis' },
          { text: 'Plugin XML 分析', link: '/34-plugin-xml-analysis' },
          { text: 'Properties i18n', link: '/35-properties-i18n-analysis' },
          { text: '完整类清单', link: '/36-complete-class-inventory' },
          { text: 'Agent 进程管理', link: '/37-agent-process-management' },
          { text: 'WebView ToolWindow', link: '/38-webview-toolwindow-analysis' },
          { text: 'Agent 服务层', link: '/39-agent-service-layer' },
          { text: '内联聊天系统', link: '/40-inline-chat-system' },
          { text: '枚举完整分析', link: '/41-enums-complete-analysis' },
          { text: 'Diff APM 分析', link: '/42-diff-apm-analysis' },
          { text: '设置配置', link: '/43-settings-configuration' },
          { text: '请求系统', link: '/44-request-complete-system' },
          { text: 'WebSocket DTO', link: '/45-websocket-dto-model' },
          { text: '单元测试生成', link: '/46-unit-test-generation' },
          { text: '动作系统完整', link: '/47-action-system-complete' },
          { text: '内容处理器', link: '/48-content-handler-analysis' },
          { text: 'Generate 包', link: '/49-generate-package-analysis' },
          { text: 'View 包分析', link: '/50-view-package-analysis' },
          { text: 'Complete 包分析', link: '/51-complete-package-analysis' },
          { text: '错误异常分析', link: '/52-error-exception-analysis' },
          { text: 'Domain/DTO/Service', link: '/53-domain-dto-service-request-analysis' },
          { text: 'Agent 通信深度分析', link: '/54-agent-communication-deep-analysis' },
          { text: 'Q/Util 包分析', link: '/55-Q-util-package-analysis' },
          { text: 'Chat Git 集成', link: '/56-chat-git-integration-analysis' },
          { text: 'Inline Chat 完整', link: '/57-inline-chat-subsystem-complete' },
          { text: 'APM 设置分析', link: '/58-listener-apm-settings-analysis' },
          { text: 'Action Inline Chat', link: '/59-action-inline-chat-subpackages-analysis' },
          { text: '模板系统完整', link: '/60-template-system-complete-analysis' },
          { text: '语言/消息/状态/测试', link: '/61-language-message-status-test-ui-analysis' },
          { text: 'Agent 服务层', link: '/62-agent-service-layer' },
        ],
      },
      // === 综合报告 ===
      {
        text: '综合报告',
        items: [
          { text: '综合分析报告', link: '/63-comprehensive-analysis-report' },
          { text: 'H 反混淆分析', link: '/64-h-deobfuscation-analysis' },
          { text: 'WebView 前端完整', link: '/65-webview-frontend-complete-analysis' },
          { text: 'Agent Webpack 分析', link: '/66-agent-webpack-bundle-analysis' },
          { text: 'H 反混淆方案', link: '/67-H-deobfuscation-solution' },
          { text: 'Plugin XML 完整', link: '/68-plugin-xml-complete-registry' },
          { text: 'I18n 完整字符串表', link: '/69-i18n-complete-string-table' },
          { text: 'API 端点格式', link: '/70-api-endpoint-formats/' },
          { text: 'CodeVector RAG', link: '/71-codevector-rag-workflow' },
          { text: '跨 IDE 差异', link: '/72-cross-ide-differences' },
          { text: '性能分析', link: '/73-performance-analysis' },
          { text: '安全审计', link: '/74-security-audit' },
          { text: 'Velocity 单测模板', link: '/75-velocity-template-unit-test-flow' },
          { text: '核心服务类', link: '/76-core-service-class-details/' },
          { text: 'WebSocket 分发链', link: '/77-websocket-dispatch-chain' },
          { text: 'Inlay 渲染系统', link: '/78-inlay-render-system' },
          { text: 'Updater/Domain/FileLoader', link: '/79-updater-domain-fileloader-analysis' },
          { text: 'H 反混淆完整结果', link: '/80-h-deobfuscation-complete-results/' },
          { text: '架构交叉引用', link: '/81-architecture-cross-reference' },
          { text: 'Q/Velocity/Kotlin', link: '/82-q-velocity-kotlin-extensions' },
          { text: 'Listener 完整反编译', link: '/83-listener-complete-decompilation/' },
          { text: 'Action 包完整', link: '/84-action-package-complete/' },
          { text: 'View/UI/StatusBar', link: '/85-view-ui-statusbar-toolwindow' },
          { text: 'JSON 配置资源', link: '/86-json-config-resources-catalog' },
          { text: '最终综合报告', link: '/87-final-comprehensive-report' },
        ],
      },
      // === 全量反编译分析 ===
      {
        text: '全量反编译分析',
        items: [
          { text: 'Template 包', link: '/88-template-package-complete-decompilation/' },
          { text: 'Inline 包', link: '/89-inline-package-complete-decompilation' },
          { text: 'Agent Service 包', link: '/90-agent-service-complete-decompilation' },
          { text: 'Service 包', link: '/91-service-package-complete-decompilation/' },
          { text: 'Util 包', link: '/92-util-package-complete-decompilation' },
          { text: 'Agent DTO 包', link: '/93-agent-dto-complete-decompilation' },
          { text: 'Startup WebView 映射', link: '/94-startup-webview-message-mapping' },
          { text: 'Test 包', link: '/95-test-package-complete-decompilation' },
          { text: 'Enums 包', link: '/96-enums-complete-decompilation/' },
          { text: '功能包', link: '/97-functional-packages-decompilation' },
          { text: '小包分析', link: '/98-small-packages-decompilation' },
        ],
      },
      // === 高层综合 ===
      {
        text: '高层综合',
        items: [
          { text: 'LLM 协议完整', link: '/99-llm-protocol-complete-analysis/' },
          { text: '加密算法完整', link: '/100-encryption-algorithms-complete-analysis/' },
          { text: 'Java 加密调用链', link: '/101-java-encryption-call-chain' },
          { text: 'WebView 协议加密', link: '/102-webview-protocol-encryption-analysis' },
          { text: '缺失类反编译', link: '/103-missing-classes-decompilation-analysis' },
          { text: '最终盲点消除', link: '/104-final-blindspot-elimination' },
          { text: 'Velocity 终极扫尾', link: '/105-velocity-templates-and-final-blindspots' },
          { text: 'Agent Webpack 清单', link: '/106-agent-webpack-modules-and-full-class-inventory' },
          { text: 'Agent 模块全面分析', link: '/107-agent-webpack-modules-and-full-analysis' },
          { text: 'Agent 动态验证', link: '/108-agent-dynamic-verification' },
        ],
      },
      // === 附录 ===
      {
        text: '附录',
        items: [
          { text: '逆向工程报告', link: '/reverse-engineering-report' },
        ],
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/vibe-coding-labs/iflycode-reverse-engineer' },
    ],
    footer: {
      message: '本项目仅供学习研究，逆向分析内容归原厂商所有。',
      copyright: 'Copyright © 2026 Vibe Coding Labs',
    },
  },
})